# Generated by Django 5.1.15 on 2026-10-02 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('short', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('photo', models.FileField(blank=True, upload_to='activities/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif', 'svg'])])),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('category', models.CharField(default='Island notes', max_length=80)),
                ('summary', models.TextField()),
                ('body', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, upload_to='rooms/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif', 'svg'])])),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Come for the waves. Stay for the people.', max_length=160)),
                ('hero_description', models.TextField(default='Salty hair. Shared stories. A place to belong. Your next chapter starts in Lajares.')),
                ('homepage_photo', models.FileField(blank=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif', 'svg'])])),
                ('graphic_element', models.FileField(blank=True, help_text='Upload a brand illustration from the supplied graphics. It appears beside the welcome text.', upload_to='site/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif', 'svg'])])),
                ('booking_url', models.URLField(default='https://www.booking.com/Share-RfTbCF')),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('business_address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('policies_approved', models.BooleanField(default=False, help_text='Only enable after the owner has reviewed the policies and completed the legal details.')),
                ('privacy_text', models.TextField(blank=True, help_text='Optional owner-reviewed privacy policy. Plain text, with blank lines between paragraphs.')),
                ('cookie_text', models.TextField(blank=True, help_text='Optional owner-reviewed cookie policy.')),
                ('terms_text', models.TextField(blank=True, help_text='Optional owner-reviewed booking and site terms.')),
            ],
        ),
    ]
