# Generated by Django 5.1.15 on 2026-10-08 09:16

from django.db import migrations, models


def update_heading(apps, schema_editor):
    apps.get_model('studio', 'SiteSettings').objects.using(
        schema_editor.connection.alias
    ).all().update(hero_title='Your people far from home')


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_remove_em_dashes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Your people far from home', max_length=160),
        ),
        migrations.RunPython(update_heading, migrations.RunPython.noop),
    ]
