# Generated by Django 5.1.15 on 2026-10-08 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_alter_sitesettings_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('key', models.CharField(max_length=200, unique=True)),
                ('image', models.FileField(blank=True, help_text='Upload a replacement. Leave empty to use the original site image.', upload_to='site-images/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'webp', 'gif', 'svg'])])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
