# Generated by Django 5.1.15 on 2026-10-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_seed_site_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Photos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('studio.siteimage',),
        ),
    ]
