# Generated by Django 5.1.15 on 2026-10-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order', 'pk'], 'verbose_name_plural': 'Activities'},
        ),
    ]
